### PR TITLE
Provide minimize query parameter to allow using different minification libs

### PR DESCRIPTION
**Pull request by termosa**
With the parameter `minimize` (has `true`value by default) I can turn off integrated minification and use global configuration for `html-minifier` or even a different library for this issue.

### CODE REVIEW

**Comment by teux** [comment]
Thanks again!
I thought about this option, but you did it )
@0.0.20

**Comment by termosa** [comment]
@teux thank you for creating this loader!
P.S. Did you think about any other options? ))

**Comment by teux** [comment]
This is really useful? I do not write for a while on the angular

**Comment by termosa** [comment]
Me too )
But I have to write several Angular applications in the nearest feature. I'm creating a boilerplate for all of them.
Once applications are made, I'll choose the strategy for loading templates. Now I just provide options in my boilerplate.

**Pull request merged**
